# Generated by Django 3.1 on 2020-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('customer', 'customer'), ('support', 'support')], max_length=100)),
                ('email', models.EmailField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='landing/images')),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=400)),
                ('header_text', models.CharField(max_length=400)),
                ('header_image', models.ImageField(upload_to='landing/images')),
                ('available_date', models.DateField(blank=True, null=True)),
                ('features_header1', models.CharField(max_length=400)),
                ('smartphone_text', models.CharField(max_length=400)),
                ('seamless_text', models.CharField(max_length=400)),
                ('high_resolution_text', models.CharField(max_length=400)),
                ('all_vr_text', models.CharField(max_length=400)),
                ('features_image1', models.ImageField(upload_to='landing/images')),
                ('features_header2', models.CharField(max_length=400)),
                ('features_image2', models.ImageField(upload_to='landing/images')),
                ('features_text2', models.CharField(max_length=400)),
                ('features_video', models.FileField(blank=True, null=True, upload_to='landing/videos')),
                ('dark_banner_heading', models.CharField(max_length=400)),
                ('dark_banner_text', models.CharField(max_length=400)),
                ('dark_banner_image', models.ImageField(upload_to='landing/images')),
                ('event_text', models.CharField(max_length=400)),
                ('subscription_image', models.ImageField(upload_to='landing/images')),
                ('contact_us_image', models.ImageField(upload_to='landing/images')),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('location', models.CharField(max_length=400)),
                ('info_email', models.EmailField(max_length=225)),
                ('support_email', models.EmailField(max_length=225)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrivatePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_service', models.TextField()),
            ],
        ),
    ]
