# Generated by Django 3.1 on 2020-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_shop', '0002_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
        ),
    ]
