# Generated by Django 3.1 on 2020-10-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_shop', '0002_about_cart_cartproduct_product_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('email', models.EmailField(max_length=225)),
                ('ref', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('street_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing_shop.cart')),
            ],
        ),
    ]
