# Generated by Django 3.1 on 2020-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_shop', '0004_auto_20201009_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
