# Generated by Django 3.1 on 2020-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_shop', '0005_orderproduct_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='appstore_url',
            field=models.URLField(default='http://playstore.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landing',
            name='playstore_url',
            field=models.URLField(default='htps://applestore.com'),
            preserve_default=False,
        ),
    ]
