# Generated by Django 3.1 on 2020-10-10 19:20

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_shop', '0006_auto_20201010_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=quilljs.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=quilljs.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='privatepolicy',
            name='private_policy',
            field=quilljs.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='terms_of_service',
            field=quilljs.fields.RichTextField(),
        ),
    ]
