# Generated by Django 3.0.6 on 2020-05-31 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': ['-date']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('live', 'live'), ('360videos', '360videos')], default='video360', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
