# Generated by Django 3.1 on 2021-02-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileandvr',
            name='activation_token',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
